### PR TITLE
Allow to use multiple adresses to connect to RabbitMQ cluster

### PR DESCRIPTION
**Pull request by barmic**
Hello,

It seems to be impossible to connect to a RabbitMQ cluster (like describe in #8). I think it can possible to add a collection of addresses in `RabbitMQOptions`. I suggest this solution.

Do you think that is the good way?

Thank you

### CODE REVIEW

**Comment by vietj** [comment]
it looks good, can you mention it in the documentation as well ?

**Comment by barmic** [comment]
@vietj it's good like that?

**Comment by vietj** [comment]
I mean a small section the general doc (src/main/asciidoc/index.adoc) with an example

**Comment by barmic** [comment]
This should be ok now.

**Comment by vietj** [comment]
thanks for the contrib

**Pull request merged**
