### PR TITLE
Update testcontainers version to fix build error on Windows

### PR DESCRIPTION
**Pull request by YaytayAtWork**
Motivation:

https://github.com/vert-x3/vertx-rabbitmq-client/issues/113
Update version of testcontainers to fix build error on Windows.

### CODE REVIEW

**Comment by YaytayAtWork** [comment]
Interesting: it builds cleanly on Windows, so the difference in the SSLExceptions is between Windows and Linux (now).

**Comment by bsideup** [comment]
FTR I would really recommend using the pre-defined RabbitMQ container (`org.testcontainers:rabbitmq`) instead of just `GenericContainer`. It simplifies the SSL configuration as well.

**Comment by YaytayAtWork** [comment]
> 
> 
> FTR I would really recommend using the pre-defined RabbitMQ container (`org.testcontainers:rabbitmq`) instead of just `GenericContainer`. It simplifies the SSL configuration as well.

In general I'd agree, I don't know why the original decision was made to use GenericContainer (though it may relate to the need to break the SSL), but this PR is about the minimal change necessary to get the build working.

**Comment by vietj** [comment]
@YaytayAtWork this PR updates also the client version, can you open a separate issue for this ?

**Comment by YaytayAtWork** [comment]
This is annoying, testcontainers 1.15.1 works correctly on Windows, but causes a CI build failure on JDK8 :(
(despite building cleanly on JDK 8 on my Ubuntu)

**Comment by vietj** [comment]
we can also add windows in the CI @YaytayAtWork currently it's not added

**Comment by YaytayAtWork** [comment]
> @YaytayAtWork this PR updates also the client version, can you open a separate issue for this ?
The move to testcontainers 1.15.1 is causing a CI build break that it proving rather annoying.
I can't repro it using JDK 8 on Ubuntu.
The change of client version was just an attempt to sort that.
Please ignore all the PRs for now, I'll recreate this one when I've got it clean.

**Comment by YaytayAtWork** [comment]
GitHub Actions don't support non-Windows containers on Windows builds, so we can't do Windows builds :(
https://github.com/actions/virtual-environments/issues/1143

**Comment by YaytayAtWork** [comment]
Closing to recreate more cleanly.

**Pull request closed without merging**
