### PR TITLE
Add Basic Cancel

### PR DESCRIPTION
**Pull request by javiersigler**
Fix issue: https://github.com/vert-x3/vertx-rabbitmq-client/issues/24

### CODE REVIEW

**Comment by thibaultleouay** [comment]
Hey @javiersigler  

Before fully diving into your PR you should write some tests. 

If you have any issues writing some, i'll be happy to help you 

Best,

Thibault

**Comment by andreas-schilling** [comment]
Any news on this? Can I support on the tests/PR?

**Comment by ThibaultDataberries** [comment]
@andreas-schilling  if you are willing to write some test for the previous PR it would be nice !

**Comment by vietj** [comment]
+1 for tests!

**Comment by vietj** [comment]
@andreas-schilling we need tests for this PR

**Comment by Yaytay** [comment]
The associated issue has been closed.

**Pull request closed without merging**
