### PR TITLE
Ssl context support

### PR DESCRIPTION
**Pull request by lanmarti**
Cannot get the connection issue mentioned in issue #69 fixed. I tested it with an MQTT server in production and it worked. If anyone has any ideas about what might be going wrong, I'll try and fix the test ASAP.

### CODE REVIEW

**Comment by vietj** [comment]
is that a finished contribution to review ?

**Comment by lanmarti** [comment]
Not fully, as there's an issue with the tests, at least on my end. I've tried to clarify in #69 .
At this point, I'm stuck, as my own local setup seems to be working just fine with the changes I've added in this PR. 
To recap the issue: when I tried running the existing tests of your master branch locally,  testReconnect of the RabbitMQClientReconnectTest class fails. The SSL test I added is throwing the exact same error. As I have no idea if this is an issue on my end or not, I'm stuck. 

I'd like to mention that my own small test, in which I connect with an actual production based MQTT broker through SSL, works fine. But such a test is of course not suited for this test suite.

**Comment by vietj** [comment]
@Sammers21 can you have a look ?

**Comment by vietj** [comment]
thanks for the contribution @lanmarti sorry we didn't merge it before, we had a new contribution for this and this time we (team) did a better job at handling it.

**Pull request closed without merging**
