### PR TITLE
Added additional config to exchangeDeclare

### PR DESCRIPTION
**Pull request by latzelsperger**
added a parameter Map<String,String> to RabbitMQClient#exchangeDeclare in order to create the exchange with additional parameters.

### CODE REVIEW

**Comment by poiuytrez** [comment]
Great PR! Could you just add an example in the generated documentation? It is located at: 
src/main/java/io/vertx/rabbitmq/package-info.java

The documentation will be generated and displayed on the official website: http://vertx.io/docs/vertx-rabbitmq-client/java/

Thank you!

**Comment by poiuytrez** [comment]
Hi @latzelsperger , 

Don't forget if you have some time to add the documentation. Thank you !

**Comment by latzelsperger** [comment]
committed the doc. I am not familiar with that kind of documentation, so please check if it fits your requirements!

**Comment by poiuytrez** [comment]
Thank you @latzelsperger !

**Pull request merged**
